# Generated by Django 4.1.4 on 2023-01-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_property_category_alter_property_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvalue',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='propertyvalue',
            unique_together={('property', 'name')},
        ),
    ]
